### PR TITLE
Feature/Update Practice QT Questions and Answers

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Issue: [Update practice QT tool questions and answers #72](https://github.com/jac-uk/qt/issues/72)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Preview Link: https://jac-practice-qt-develop.web.app/

1. Check if the questions and answers are updated in SJT practice test.
2. Check if the "Skip to the next question" appears on the right-hand side of the green top navigation.
3. Check if the text on the final page is updated.

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC Can you pls change the register your interest via our website link to: 

https://judicialappointments.gov.uk/how-to-prepare-before-you-apply/#QTlink

**Comment by HalcyonJAC** [comment]
@nickaddy The link has been changed. Could you check it, please?

**Review by NormaJAC — APPROVED** [review]
It works, the questions and answers are updated in SJT practice test.
The "Skip to the next question" appears on the right-hand side of the green top navigation.
The text on the final page is updated.
The register your interest via our website link works.

**Comment by nickaddy** [comment]
👍 Just waiting for Rachael's response.

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC Feedback from Rachael:

Thanks very much for actioning this and for sending over the helpful test. Sean and I have been through and checked it (testing it multiple times and trying to get different scores) and we are very happy with it is working, and are content for it to be uploaded to the live website. Huge thanks to you and your team for working on this.

If you can get one more review from Tom or Omar, I'm happy for this to go live. We might need to jump on a call together to do the upload using my login.

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC Happy with this - pls proceed with closing the ticket, no merging required!

**Pull request merged**
